parsing methods:
  selenium:
    claim variants: ['usual', 'normal', 'selenium']
    description: 'Parsing using Selenium. Detected by anti-bot systems'
    headless: False
    fullscreen: False
    window width: 1500
    window height: 900
  undetected selenium:
    claim variants: ['undetected', 'undetected selenium']
    description: 'Parsing using Selenium. Hard to detect by anti-bot systems'
    fullscreen: False
    window width: 1200
    window height: 600
    use proxy: True
    proxy username: 'hgvueehe-1'
    proxy password: 'jer1l82sel82'
    proxy ip: 'p.webshare.io'
    proxy port: '80'
    browser folder: 'browser_folder'
  open api:
    claim variants: [ 'api', 'open api' ]
    description: 'Parsing using open API.'
    use proxy: True
    parallel: True
    parallel count: 10
    proxy username: 'hgvueehe-1'
    proxy password: 'jer1l82sel82'
    proxy ip: 'p.webshare.io'
    proxy port: '80'
sports: ['football', 'basketball', 'tennis', 'table-tennis', 'ice-hockey', 'esports', 'handball',
         'volleyball', 'baseball', 'american-football', 'motorsport', 'cricket', 'rugby', 'darts',
         'snooker', 'futsal', 'badminton', 'aussie-rules', 'beach-volley', 'waterpolo', 'floorball',
         'bandy']
tries: 3
waits:
  wait for sport page: 15

database:
  database: 'dbname'
  user: 'postgres'
  password: '123'